/// <reference types="react" />
export declare const ModalBackdrop: import('styled-components').IStyledComponent<"web", import('styled-components/dist/types').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const ModalWrapper: import('styled-components').IStyledComponent<"web", import('styled-components/dist/types').Substitute<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLElement>, HTMLElement>, {
    position: "top" | "center" | "bottom";
}>>;
export declare const ModalHeader: import('styled-components').IStyledComponent<"web", import('styled-components/dist/types').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLElement>, HTMLElement>, never>>;
export declare const ModalTitle: import('styled-components').IStyledComponent<"web", import('styled-components/dist/types').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, never>>;
export declare const ModalCloseButton: import('styled-components').IStyledComponent<"web", import('styled-components/dist/types').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, never>>;
export declare const ModalLongButton: import('styled-components').IStyledComponent<"web", import('styled-components/dist/types').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, never>>;
export declare const ModalContent: import('styled-components').IStyledComponent<"web", import('styled-components/dist/types').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLElement>, HTMLElement>, never>>;
export declare const ModalFooter: import('styled-components').IStyledComponent<"web", import('styled-components/dist/types').FastOmit<import('../../../node_modules/react').DetailedHTMLProps<import('../../../node_modules/react').HTMLAttributes<HTMLElement>, HTMLElement>, never>>;
